package com.example.s215726_lykkehjul

    val words: List<String> = listOf(
        "ARGENTINA",
        "BRASILIEN",
        "CANADA",
        "COLOMBIA",
        "DANMARK",
        "EGYPTEN",
        "FINLAND",
        "FRANKRIG",
        "GHANA",
        "INDIEN",
        "JAPAN",
        "KINA",
        "LETLAND",
        "LUXEMBOURG",
        "MAROKKO",
        "MALTA",
        "MEXICO",
        "NORDKOREA",
        "PORTUGAL",
        "QATAR",
        "RUSLAND",
        "SCHWEIZ",
        "SERBIEN",
        "TUNESIEN",
        "UKRAINE",
        "VENEZUELA",
        "EDDERKOP", //
        "ELEFANT",
        "FLODHEST",
        "FLAGERMUS",
        "ZEBRA",
        "SKILDPADDE",
        "SOMMERFUGL",
        "FLAGERMUS",
        "BASKETBALL", //
        "FODBOLD",
        "CURLING",
        "BADMINTON",
        "SQUASH",
        "BUESKYDNING",
        "SYNKRONSVØMNING"
    )